server:
  port: 8082

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/kfish?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    check-template-location: true
  #  redis:
#    host: 127.0.0.1
#    port: 6379
mybatis-plus:
  mapper-locations: classpath:com/yao/kfish/mapper/xml/*.xml


logging:
  level:
    th:
      yao:
        Mapper : debug
#  config: classpath:log4j.properties
